@startuml wifi_connection_fetch_data_sequence

WIFI -> WIFI: Give sem when connected
Fetch_Task -> Printer_base: printer data update
Printer_base -> Printers: get state
Printers --> Printer_base: return state
Printer_base -> Printers: if OFFLINE, printer connect text
Printers --> Printer_base: Return status 
Printer_base -> Display: if failed render wifi error screen
Printer_base -> Printers: if sucess fetch printer data
Printers -> NET: HTTP GET printer data
NET --> Printers: JSON rsp data

Printers -> Utils: Prase JSON data
Utils --> Printers: Parsed data
Printers -> Printers: Save data to printer_info struct
Printers --> Printer_base
Printer_base -> Display: Render Extracted data

WIFI -> WIFI: Disconnected, sets wifi_connected:false
Fetch_Task -> Display: Render Wifi Disconnected Screen
Fetch_Task -> Fetch_Task: Waits for the wifi to connect

@enduml